# -*- coding: utf-8 -*-
"""Project_A_Credit_Scorecard_Final.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KYz0G9jRn9CsdYvCZgI3irX1gBI4O-M1
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# --- 1. LOAD DATA ---
filename = 'MWCD_Synthetic_Data_1000.csv'

try:
    df = pd.read_csv(filename)
    print(f"✅ Loaded {len(df)} profiles.")

    # Clean up columns to ensure they are numbers
    # We use 'errors=coerce' to turn any messy text into NaN (0)
    df['Monthly Dairy Income'] = pd.to_numeric(df['Monthly Dairy Income'], errors='coerce').fillna(0)
    df['Land (Acres)'] = pd.to_numeric(df['Land (Acres)'], errors='coerce').fillna(0)
    df['Cattle Count'] = pd.to_numeric(df['Cattle Count'], errors='coerce').fillna(0)

except FileNotFoundError:
    print(f"❌ Error: Please upload '{filename}' to Colab!")

# --- 2. THE SCORING ALGORITHMS (Mapped to your Codebook) ---

# A. Capacity Score (35%) - Cash Flow
def get_capacity_score(income):
    if income >= 25000: return 100  # Excellent
    elif income >= 15000: return 80 # Good
    elif income >= 10000: return 60 # Average
    elif income >= 5000: return 40  # Low
    else: return 20                 # High Risk

# B. Collateral Score (25%) - Assets
# Logic: 1 Acre = 10 pts, 1 Cow = 5 pts
def get_asset_score(row):
    land_points = row['Land (Acres)'] * 10
    cattle_points = row['Cattle Count'] * 5
    total = land_points + cattle_points
    return min(100, total) # Cap score at 100

# C. Character Score (25%) - Spending Behavior
# Mapped to your Codebook.csv:
# 0=Education, 4=Crop Invest, 5=Asset Purchase, 6=Savings --> HIGH VALUE
# 3=Household Exp --> MEDIUM
# 1=Food/Groceries, 2=Loan Repayment, 7=None --> HIGH RISK
def get_behavior_score(code):
    if code in [0, 4, 5, 6]: return 100  # Investor Mindset
    elif code in [3]: return 60          # Consumer Mindset
    elif code in [1, 2, 7]: return 30    # Survival/Debt Mindset
    else: return 50                      # Unknown

# D. Stability Score (15%) - Education
# Mapped to your Codebook.csv:
# 3=12th, 4=Degree --> HIGH STABILITY
# 2=10th --> MEDIUM
# 0=Illiterate, 1=Primary --> LOW
def get_stability_score(code):
    if code in [3, 4]: return 100
    elif code in [2]: return 70
    elif code in [0, 1]: return 40
    else: return 40

# --- 3. RUN THE ENGINE ---
print("⚙️  Calculating Credit Scores...")

df['Score_Capacity'] = df['Monthly Dairy Income'].apply(get_capacity_score)
df['Score_Assets'] = df.apply(get_asset_score, axis=1)
# Note: We use the numerical columns 'income_use' and 'edu_level' created in Excel
df['Score_Behavior'] = df['income_use'].apply(get_behavior_score)
df['Score_Stability'] = df['edu_level'].apply(get_stability_score)

# Weighted Formula
df['MWCD_Credit_Score'] = (df['Score_Capacity'] * 0.35) + \
                          (df['Score_Assets'] * 0.25) + \
                          (df['Score_Behavior'] * 0.25) + \
                          (df['Score_Stability'] * 0.15)

df['MWCD_Credit_Score'] = df['MWCD_Credit_Score'].round(0)

# Assign Risk Tiers for the Bank
def assign_tier(score):
    if score >= 75: return 'Tier 1: Prime (Interest 10%)'
    elif score >= 55: return 'Tier 2: Standard (Interest 14%)'
    else: return 'Tier 3: Sub-Prime (Collateral Req)'

df['Risk_Tier'] = df['MWCD_Credit_Score'].apply(assign_tier)

# --- 4. VISUALIZE & EXPORT ---

plt.figure(figsize=(10, 6))
sns.histplot(data=df, x='MWCD_Credit_Score', hue='Risk_Tier', multiple='stack', palette='viridis', binwidth=5)
plt.title('The "Milky Way" Alternative Credit Score (N=1000)', fontsize=14, fontweight='bold')
plt.xlabel('Credit Score (0-100)')
plt.ylabel('Number of Women')
plt.axvline(55, color='red', linestyle='--', label='Lending Cut-off')
plt.legend()
plt.tight_layout()
plt.savefig('Credit_Score_Distribution.png')

print("✅ Analysis Complete!")
print(df[['Name', 'Monthly Dairy Income', 'Primary Income Use', 'MWCD_Credit_Score', 'Risk_Tier']].head(10))

# Save the scored file for your GitHub
df.to_csv('MWCD_Scored_Data_Final.csv', index=False)
print("\n📂 Download 'MWCD_Scored_Data_Final.csv' for your Portfolio!")