# -*- coding: utf-8 -*-
"""MWCD_Synthetic_Data_Generator.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Da1pgyo86BhkZUV47bFsI_AidtJLIvYk
"""

import pandas as pd
import numpy as np

# --- 1. SETUP: Load the small real dataset ---
# Make sure your file is named 'data.csv' in the Colab files section
try:
    df_real = pd.read_csv('MWCD_Original_Data.csv')
    print(f"✅ Success! Loaded {len(df_real)} real respondents.")
except FileNotFoundError:
    print("❌ Error: Please upload your 'data.csv' file to the folder icon on the left.")

# --- 2. GENERATION: Create 1,000 Synthetic Rows ---
# We use 'sample' with replace=True. This preserves the correlations.
# (e.g. High Income will still link to 'Asset Purchase')
target_size = 1000
df_synthetic = df_real.sample(n=target_size, replace=True).reset_index(drop=True)

print("------------------------------------------------")
print(f"Generating {target_size} rows based on real patterns...")

# --- 3. ADDING REALISM (The "Noise" Factor) ---
# We don't want 30 people to have the EXACT same income down to the rupee.
# We will wiggle the numbers slightly (+/- 10%)

# Check if you have an Income column. Change the name below if yours is different.
income_col = 'Monthly Dairy Income (INR)'

if income_col in df_synthetic.columns:
    # Generate random noise: between -10% and +10% of the value
    noise = np.random.uniform(0.9, 1.1, size=target_size)

    # Apply noise
    df_synthetic[income_col] = df_synthetic[income_col] * noise

    # Round to nearest 100 (makes it look cleaner, e.g., 14231 -> 14200)
    df_synthetic[income_col] = df_synthetic[income_col].round(-2)

    print(f"✅ Added statistical noise to '{income_col}' to make unique values.")

# --- 4. ADDING A UNIQUE ID ---
# Give every fake person a unique ID number
df_synthetic.insert(0, 'Respondent_ID', range(1, 1 + len(df_synthetic)))

# --- 5. EXPORT ---
output_filename = 'MWCD_Synthetic_Data_1000.csv'
df_synthetic.to_csv(output_filename, index=False)

print("------------------------------------------------")
print(f"🎉 DONE! File saved as: {output_filename}")
print("👉 Look in the files tab on the left to download it.")
print("   (You may need to click the 'Refresh' folder icon)")